import Header from '@/components/common/Header'
import './globals.css'
import { Work_Sans } from 'next/font/google'
import Footer from '@/components/common/Footer'

const sans = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={(sans.className, 'h-full')}>
      <body className="h-full max-w-5xl mx-auto">
        <Header />
        <main className="h-auto min-h-[calc(100%-50px)] pb-[150px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
