import Header from '@/components/Header'
import './globals.css'
import { Work_Sans } from 'next/font/google'
import Footer from '@/components/Footer'

const sans = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
